### ISSUE TITLE
Error Process

### ISSUE THREAD

**Issue by budx1** [conor19w/Binance-Futures-Bot#33]
Hey, really amazing code! thank you!
i'm having this issue with the backtesting, can you help me?

Process Process-1:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\X\Downloads\Binance-Futures-Bot-main\Binance-Futures-Bot-main\Backtester.py", line 300, in run_backtester
    average /= num_wins
ZeroDivisionError: division by zero

**Comment by conor19w** [comment]
Hey looks like the Bot didn't take any trades over the period you tested
